<Project>
  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <DebugType>embedded</DebugType>
    <DebugSymbols>true</DebugSymbols>
    <UsePublicApiAnalyzers>true</UsePublicApiAnalyzers>
    <PackageVersion>1.0.0</PackageVersion>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
    <FileVersion>1.0.0.0</FileVersion>

    <PackageOutputPath>$(MSBuildThisFileDirectory)nupkg</PackageOutputPath>

    <AndroidApiLevelMin>21</AndroidApiLevelMin>
    <iOSVersionMin>13.0</iOSVersionMin>
    <tvOSVersionMin>13.0</tvOSVersionMin>
    <macOSVersionMin>12.0</macOSVersionMin>
    <MacCatalystVersionMin>15.2</MacCatalystVersionMin>

    <Copyright>Gabriel Martin</Copyright>
    <LangVersion>preview</LangVersion>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>

    <BuildOs Condition="$([MSBuild]::IsOsPlatform('Linux'))">linux</BuildOs>
    <BuildOs Condition="$([MSBuild]::IsOsPlatform('OSX'))">darwin</BuildOs>
    <BuildOs Condition=" '$(BuildOs)' == '' ">windows</BuildOs>
    <BuildArch Condition=" '$([System.Runtime.InteropServices.RuntimeInformation]::OSArchitecture)' == 'X86' ">386</BuildArch>
    <BuildArch Condition=" '$([System.Runtime.InteropServices.RuntimeInformation]::OSArchitecture)' == 'Arm64' ">arm64</BuildArch>
    <BuildArch Condition=" '$(BuildArch)' == '' ">amd64</BuildArch>
  </PropertyGroup>
</Project>
